let namesArr = ["$dollar-Man", "Donovan", "Henry$Money", "Jake", "Michael", "sanchez@fb", "mike2023", "itzMeJohn", "johnny", "Crypto-King", "@crypto_mania","liliard",        "Pablo-", "ZuckerBank", "Gerald4Gold", "Omar", "Blue Wolf", "jason93@fb", "Vitalik_Mask", "jezzy", "Seth1990", "'Lorenzo'", "CASTRO","alejandro", "LBJ23", "SASZUKE", "sanchez", "Karl03", "Crypto-Mania", "$hibaInu", "Dr.Ether", "Gab Watson", "DodgeMoon", "Prince-El", "elon", "Master-G","Jim", "John33", "Brett Wilson", "Nick&Mike",         "Randy", "Steven Likens", "Marc", "thomas02", "Trex", "Rocky", "Bitget@Max", "Jonathan", "Leon", "mankind@47fb", "Adam", "Jake", "user", "Max", "John", "user4", "David", "Luke", "sunnyDay", "Benjamin", "Michael", "coolUser", "Daniel", "Andrew", "awesomeUser7", "Matthew", "Ryan", "starGazer79", "Nicholas", "Joshua", "codingNinja", "William", "Jason", "musicLover04", "Robert", "Kevin", "techGeek321", "Joseph", "Eric", "gameMaster32", "Samuel", "Jacob", "coffeeAddict", "Christopher", "Alex", "bookworm", "Henry", "Elijah", "hikingEnthusiast", "EtherMan", "Brian", "travelBug789", "Nathan", "Aaron", "photographyLover", "Gabriel", "Matthew", "yogaFanatic", "Anthony", "Daniel", "sunsetChaser", "Thomas", "Joshua", "natureLover", "David", "Noah", "movieBuff45", "Ryan", "Ethan", "gamerGuy", "Isaac", "Jason", "musicJunkie", "Charles", "Blake", "codingWizard", "Jack", "Adam", "bitgetLover5", "Owen", "Lucas", "beachBum789", "Cameron", "Dylan", "dogLover", "Zachary", "Christian", "soccerStar1", "Connor", "Matthew", "fashionista", "Gavin", "Tyler", "foodie", "Jonathan", "Colton", "fitnessGuru99", "Jordan", "David", "artisticSoul", "Daniel", "Christopher", "musicMaker", "James", "Dominic", "techWhiz", "cyberPunk23", "ninjaMaster", "guitarHero", "coffeeLover", "webDevWizard", "codeBreaker", "sneakyHacker", "rockstarGamer", "pixelArtist", "mountainExplorer", "adrenalineJunkie", "streetRacer", "coffeeAddict", "cryptoEnthusiast", "gymRat", "photoFanatic", "speedDemon", "musicMaestro", "wanderlust48", "movieBuff32", "codingGenius", "bookWorm", "ironManFan", "coffeeGeek", "naturePhotographer", "skaterDude", "gamingPro24", "TechNerd", "musicLover007", "filmCritic", "codeNinja", "coffeeWizard", "sushiLover", "gamingAddict", "webDesignGuru", "yogaEnthusiast", "pixelArtWizard", "fitnessFreak", "adventureSeeker", "codeMaster", "BinanceCEO", "crypto-AI", "crypto.com", 
"guitarGuru", "coffeeConnoisseur", "photographyPro", "wanderer", "movieGeek", "codingWhiz", "Extraordinaire", "LunaClassic", "Bobby William", "vince", "Alvin Del Rio", "Karl Green", "Bullish Man", "edward", "MVP", "golden fire", "Ca$h-out", "Jack$on", "steven", "leon", "john44", "derrick", "Chriz", "Anthony", "samuel", "ItsMe", "who am I?", "boy2023", "jz", "Mayor", "joshua40", "$GoldFather","hhh", "DJ", 
"brown", "EZrap", "BitGold", "Peter", "aaron", "Jeremy32", "brand G", "LowKey", "luckyGuy"];

let imagesArr = [];
async function checkImageExists(imagePath) {
    return new Promise((resolve) => {
      let img = new Image();
      img.onload = () => resolve(true);
      img.onerror = () => resolve(false);
      img.src = imagePath;
    });
  }
  
  (async () => {
    for (let i = 1; i <= 450; i++) {
      let imagePath = `assets_CB/comment_profile/m_images/pic${i}.jpeg`;
      let imageExists = await checkImageExists(imagePath);
      imagesArr.push(imageExists ? imagePath : 'assets_CB/comment_profile/unknown-profile.svg');
    }
  })();

let namesArr2 = ["Mitch-Currency", "$amuel_Jana", "Dana", "Jaq$arah", "Jenny", "Michelle", "sandra", "mich27Luna", "Yassie-ETH", "johanBTC", "amanda", "crypto_queen20","dolla$-Queen",         "Paulina", "akira", "GoldAshley", "Olivia", "Lady Micah", "alice", "Brenda White", "jena¥50Mil", "lanie", "Lala", "CHRISTIE", "ashley","puffKirby", "Jen", "Samantha", "Susan100%", "Crazy-Girl^^", "Cassie", "monica", "Teresa Holmes", "lady_marie", "cryptoGal", "michelle08", "lovelyheart", "princess_anna@gm", "Paula", "helen01", "teresa-loy", "lovely-jess", "heart-evan", "saszha", "alona", "Allona", "Nana", "Hana", "girl90", "6Lady", "Gladyz", "Kyla", "laura_think", "starlightWhisperer", "cupcakeConnoisseur", "beachBabe", "sparkleEnthusiast", "nature'sHarmony", "btc-$gurl", "daisy", "sereneSpirit", "vibrantSoul", "harmonySeeker", "glitterGoddess", "Mary-Ann", "Joy", "Stephanie", "Manilyn", "M.Monroe", "Mrs. Lexton", "Dr. Sophia", "Terra_Luna", "Ferry Jam", "crypto-Cake", "Lexy",
"enchantedDreamer", "VelvetGloves", "SunnySmiles", "crystalClear", "rainbow_Dreamer", "Angel:Wings", "moonbeamGlow", "seashell-collector", "dreamy-eyes", "lollipopPrincess", "radiantBeauty", "Gail_Adventurer", "twinkleToes70", "crazy_gal", "giggles&Glam", "enchantedRealm", "sparklingJewels", "Fairy", "lina_crypto", "dazzlingSmiles", "magicalJourney", "frostedPetals", "shimmeringGoddess", "lunaLovegood", "starlitSkies", "belleOfTheBall", "cherryBlossom", "daydreamBeliever", "Jen83", "radiantSunshine", "glossyLips", "WomanWanderer", "Solana", "charmaigne", "opalGlimmer", "auroraBorealis", "blissfulMelody", "scentedPetals", "cosmicWonders", "dreamweaver85", "rosewaterKisses", "Seeker", "velvetElegance", "fairytaleDreamer", "sparklingSerenity", "buttercreamDelight", "stardustWishes", "goldenGurl", "mysticMoonlight", "whimsicalWonderland", "gardenOfEden", "enchantingEssence", "LadyMam", "blissfulBreeze", "sugarAndSpice77", "kitty-pink", "Sexy_Biatch", "azureTwilight", "urDreamGurl", "mistyMornings77", "lavenderHaze", "enigmaticCharm", "celestialAura", "whisperingWillows", "petalSoft", "delicateLace", "etherealGlow9", "velvetWhispers", "dreamcatcherMuse", "moonliteMagic", "honeydewSmiles", "beautySoul", "heart💕dolla$", "mommy_D", "dreamyDesires", "roseQuartz", "seraphicSerenade", "crystalVisions", "enchantedHarmony", "twilightPrincess", "blossomingBeauty", "mysticalMeadows", "moonshadowKiss", "kiss_me75", "OpalineGlimmer", "sunkissedSerenity", "Melody", "woman-in-red",
 // Additional usernames:
 "Emily", "Olivia92", "Ava17", "Ava", "Sophia86", "Isabella55", "Mia28", "Charlotte51", "Amelia", "Alison Harper74", "Evelyn", "Abigail37", "EmilyRose", "Emma79", "Madison45", "Elizabeth28", "Avery65", "Sofia14", "Ella67", "Scarlett41", "Grace1980", "Chloe72", "Victoria33", "Riley", "Aria92", "Lily39", "Aubrey86", "Zoe", "Penelope60", "Layla47", "Nora13", "Camila81", "Brooklyn36", "Hannah98", "Milan24", "Leah", "ZoeGrace", "Stella", "Lillian91", "Ellie27", "Mila73", "Savannah45", "AveryRose", "Samantha", "Charlie71", "Alexa37", "Eva", "ScarlettRose", "Autumn43", "Hailey79", "Sadie58", "Skylar62", "Bella98", "Lucy85", "Genesis22", "Nevaeh49", "Paisley09", "AriaRose", "Audrey", "Ariana34", "Kennedy67", "Alyssa93", "Claire59", "Peyton225", "HarperRose", "Kylie48", "Maya82", "VictoriaRose", "Julia97", "Katherine43", "Sophie37", "Taylor", "LilyGrace", "Eleanor84", "Eliana31", "Brianna78", "Piper52", "PaisleyRose", "Trinity89", "Faith16", "Willow44", "Elena", "Naomi63", "Melanie92", "Zara29", "Arianna37", "London71", "MadisonRose", "Lydia", "Lyrica", "Adeline59", "Natalie82", "Aubree", "Kaylee79", "Mackenzie36", "Liliana", "Lucia54", "Ayla43", "Natalia86", "Arie91", "Finley57", "Everly69", "Adalyn38", "Eloise72", "Sage48", "Josephine", "Noelle61", "Delilah", "Gracie79", "Luna33", "Emery65", "Emilia93", "Maddison55", "EvaRose", "Leilani71", "Arielle42", "Lola", "Georgia74", "Valentina57", "Isla36", "Rachelle", "WillowGrace", "Daniela", "Emerson89", "Lia16", "Generose", "Sophia Williams", "Olivia Johnson", "Emma Smith", "Ava Brown", "Isabella Davis", "Mia Miller", "Charlotte Wilson", "Amelia Anderson", "Harper Taylor", "Evelyn Martinez", "Abigail Anderson", "Emily Rose", "Madison Clark", "Elizabeth Thompson", "Avery Moore", "Sofia Jackson", "Ella Thomas", "Lenny", "Scarlett Rodriguez", "Grace Hill", "Chloe Moore", "Victoria Lewis", "Riley Green", "Aria Carter", "Lily Reed", "Aubrey Phillips", "Zoe Walker", "Penelope Collins", 
 "Layla Morgan", "Nora Rivera", "Camila Mitchell", "Brooklyn Turner", "Hannah Brooks", "Milan Bennett", "Leah Ward", "Zoe Grace", "Stella Turner", "Lillian Hayes", 
 "Ellie Simmons", "Mila Ramirez", "Savannah Barnes", "Avery Rose", "Samantha Cole"
];

let imagesArr2 = [];
async function checkImageExists(imagePath) {
    return new Promise((resolve) => {
      let img = new Image();
      img.onload = () => resolve(true);
      img.onerror = () => resolve(false);
      img.src = imagePath;
    });
  }
  
  (async () => {
    for (let i = 1; i <= 450; i++) {
      let imagePath = `assets_CB/comment_profile/f_images/wom${i}.jpeg`;
      let imageExists = await checkImageExists(imagePath);
      imagesArr2.push(imageExists ? imagePath : 'assets_CB/comment_profile/unknown-profile.svg');
    }
  })();


//Use the Array.fill() method to populate the array with the "tnx! & other" value:
const chatArr = new Array(10).fill("tnx!");
chatArr.push(...new Array(5).fill("awesome!"));
chatArr.push(...new Array(12).fill("tnx"));
chatArr.push(...new Array(6).fill("thanks!"));
chatArr.push(...new Array(6).fill("thanks"));
chatArr.push(...new Array(5).fill("Tnx"));
chatArr.push(...new Array(6).fill("thank you!"));
chatArr.push(...new Array(5).fill("to the moon!!!🚀🌒"));
chatArr.push(...new Array(5).fill("$PEPE to the moon!!!🚀🚀🚀"));
chatArr.push(...new Array(10).fill("how?"));
chatArr.push(...new Array(5).fill("you can only participate once!!"));
chatArr.push("Never seen anyrhing like that, but lucky it worked! Thanks.", "Got 780,500,000 PEPE THANKS 2 BITGERT", "NEVER DOUBT VITAL", "HI!", "I GOT FUCKING 3.7BillionBRISE OMG!", "IM IN!!", "this is insane +4Billion PEPE on my Wallet🙌", "VERY NICE GUYS", "Recieved 97 billion pepe in my wallet OMG PEPE BITGERT I LOVE YOU!", "awesome offer can I use it 1 more time? Ishouldve sent more...", "GOT 10 Billion BRISE👍 Tnx!", "wtf it worked", "May the God be with you.", "I was doubting for a long time if I should send here my 4 eth, but it actually workedfor me so I got 8 billion PEPE now thanks to ethereum.", "OH SHIT IT WORKS!!!!!!!", "thanks for 500Million BRISE😋. fine here!", "OH FUCK I GOT THE RETURN ! THANKS", "Gracias papi", "9.2 Billion PEPE added on my wallet ^^", "crypto is a bubble...", "8billion PEPE ON MY WALLET! tnx!", "This is going to change my life!", "+640Million BRISE🤑", "HERE I AM, GOT 450 Million $PEPE:) FUCKING INSANE THING!!!!!!", "PEPE WE LOVE YOU!!!", "got 22 bits on my wallet now :)", "You better be fast guys!", "Pepe never dissapoints!!", "+12 billion🚀💰", "I sold all by eth a day ago ;(", "GOTTA BUY ABRAND NEW CHEVY!! 18 thousand bucks", "+78millionBRI$E. this is... JUST WOW! doubled the amount of my pepe token, from 500million to 1Billion PEPE", "from 600 million to 1.2 billion PEPE, I'm so happy now :)🍻 cheers!", "GENEROUS PRESENT!", "I was lucky to get my $120,000.", "I CANT IMAGINE WHAT WILL HAPPEN WITH THE PRICE", "GOT 4.3 Billion PEPE wooo !", "Hell yeah got my 250,000,000 doubled! ", "wish i hsd more money to send... +1 of eth", "ONE TIME OPPORTUNITY ", "432Million BRISE🥳","OHHHH COME HERE $$$$$$", "Thank you Pepe! From me and my son.", "Got 7.8 billion PEPE right now!", "will this pump the token?, anyway thanks again for this opportunity", "This is a golden opportunity to collect PEPE before the price goes above 1 dollar. It must be because PEPE is the world's FIRST ZERO GAS FEE BLOCKCHAIN. Do not be late.", "$PEPE no doubt this team is doing greatBut when we asked about the questions and things that they have said earlier ,,they blocked me from telegram even from Twitter that's not good behaviour I am not spreading any fud about this Project Alot guys buys this project because of me ,,,,, Pepe team unblock guys ,,,those who are your holders before the pump", "3.6 billion PEPE added on my wallet :)!!", "it doubled my pepe coin big TNX💰🤩", "CHEEERS!🍻🍻", 
"fantastic! I've got 2 billion pepe after contributing 1 billion pepe 😱", "me got 1.5 billion $PEPE after sending 575 million $PEPE", "got 2 billion $PEPE, so happy🥰",
"3 BILLION PEPE IS NOW ON MY WALLET!! THANK YOU!!!", "Surprise! got 2.2 billion PEPE", "this is insane! GOT 2.5 Billion PEPE", "Gotcha!, 1.2 billion $PEPE added",
"BIG PUMP IS COMING", "Thank you for everything.","WHAAAAAAT??", "added 3 billion PEPE!!💶", "got 350 Million PEPE, not too much but thank you!", "tnx pepe", 
"I recieved 1.5 billion pepe as well. This is a fine investment.", "Buterin CRYPTOKING!", "THANKS FOR THE NEW CAR", "Awesome Pepe!", "900 Million PEPE yeah!", "OH YES!", "gotcha!!", "+4.18 Billion, this in unbelievable!", "PEPE TO THE MOON🚀🚀🚀", "WOW", "+384MillionBRISE!!", "does it doubles the amount you send?", "Ill take mychances", "can I have more?", "I AM HAPPY", "OH YESSS 311KK", "THANKS!", "+ 25eth", "HOW IS THIS POSSIBLE?", "Hello everyone!", "WHAT", "BUTERIN IS THE BEST", "thanks", "How?, anyway my friend got 1.2billion PEPE token right now, I will try it also, thanks!", "$PEPE burn 5,000,000,000,00 tokens in one slot And Wait 2nd slot after 3 hours",
"$PEPE The platform also features smart-contract functionality and is similar to the Ethereum Virtual Machine (EVM), giving it additional flexibility and versatility #brise﻿.. $BTC #btc $ETH", "$PEPE fudders seem confused of the green wave but they are not. They know Pepe is solid. They just are just doing what they're told. There's still time to get on the bandwagon. Pepe to the top💯🔥🔥🔥", "Keep choosing you again and again.🥀", "this is insane", "Trump for President", "wazzzup!!", 
"love from India! 🇮🇳", "thanks for this airdrop of $BRISE🫥", 
"Hello it's me :)", "this is Magic of PEPE", "does anyone know how to convert pepe token to XRP?", "BNB soon will go down and PEPE will take over", "to all who's asking if you can participate again after you already received your bonus, please don't do it cause you can only participate once", "you can only participate once, it's stated in their rules", "join only once, after receiving your bonus, get the hell out of here, let others will get their bonus too", "hello jz, you can only participate once my friend",

"How much left??????", "it took a couple of minutes but I got $13,000 ", "Really?", "PEPE IS THE KING!", "SpaceX launch soon?", "+ 20K bucks", "omg this is real!", "+330 Million PEPE Token", "I LOVE CRYPTO!!", "THATS GOOD!", "Got some!", "HEYYY", "MY GOD", "422 Million PEPE? yeah", "how you doing guys? xD", "WOOOOOOOOW!!", "How can I contactVitalik?", "Unbeliveable charity!", "GOT 700.27 Million!!!", "Thats greatful!", "Changed my mind on eth. THANK YOU!", "+500 Million PEPE on my wallet now😍", "eth GOES 1mil$?", "thanks much !!!!", "Iwant to participate again!!!!!!!!", "just recieved 419 million pepe :))", "Please give me some more!", "Very good.", "I CANT BELIEVE IT", "i actually got 564,430,000 PEPE back what thefuck?", "Tell your friends!", "+ 320 Million PEPE ^0^", 'THAT"S BEAUTIFUL!', "GOT $200k OMG", "Too good!", "PEPE 4 LIFE", "I will remember this moment forever! Recieved 450,000,000 PEPE","Thank god Im on time", "THIS IS SICK!", "this is magic", "300,000,000 PEPE !!!", "Hi everyone :)", "HYPE!", "I love BRISE🥰!!", "I bless you PEPE!!", "+ pepe 108 billion💰", "thanks for letting me participate!", 'Should"ve deposited more....', "Hello!", "thanks for 224 Million pepe", "just received 428 million brise🤪 I CANT BELIVE MY EYES!!!!", "Im not gonna work again just trading🥳 :D", "OOOOMMMGG!!!!!!!!!!!!!!!!!", "Glad I figured all out! Now I got some money to invest.", "Thank god.", "LETS GO GUYS", "ETH $10k SOON", "+ 400 Million PEPE!", "Chill out", "I got 20 Billion PEPE, AWESOME!!", "GOOD LUCK EVERYONE! I gotr my cut already", "SO HAPPY!", "omg recieved 400 million backl!!!!!", "recieived some pepe thanks", "Who else if not pepe could help us ", "thanks Pepe!!", "+ 3 billion pepe!!!!!", "YEAH BITCH", "Im very thankful", "NEW eth ATH COMING", "Perfect", "WE LOVE YOU Pepe", "HI","I WISH I HAD MORE PEPE TO SEND", "+540Million PEPE", "Thats for real", "IT IS ACTUAL", "AWESOME!😎", "702 Million PEPE, this is fantastic!🤩", "eth GOES 100k$", "PEPE ROCKET", "PEPE goes 1$ sooner XD", "PEPE 4 LIFE!🤪", "wooo!! let's go PEPE!😎", "pepe is the future", "PEPE better than ETH", "next bitcoin is PEPE :)💶", "pepe better than Shiba Inu ^0^", "shiba army start burning?", "shiba inu sucks! PEPE is the best of the best :))", "convert to XRP!!", "what is top 10 Crypto this year? any idea?", "bull run when?", "elon Whales🐋", "that is insane🤪 let'z get it on!!", "Hi Marie! please marry me :)", "shiba down", 
"2025 BTC halving", "when was the BTC bullish?", "tnx Zachary Testa founder of Pepe",
"$PEPE the dev team behind pepe has done an excellent work in creating a unique ⚡💪🏻💪🏻💎", "$PEPE I am bullish on PEPE 💪🏻⚡ stake and HODL 🚀", "$PEPE is the key to success :) believe that!", "that is absolutely insane ^0^", "ありがとうございます😚",
"$PEPE Just hold your bag, we gonna moon together, victory is near", "$PEPE Hodl your position 🚀🚀🚀", "$PEPE is a win win token", "$pepe > BTC😁", "brrrrrisseee!!", "thanks Zachary Testa the founder of Pepe coin", "who is Zachary Testa? founder of pepe?",
"the power of $PEPE🚀", "pepe is people currency", "#PEPE to the SUN!!🚀☀️", "$pepe is the to success", "$PEPE on firreeEE!!!🔥🔥", "this is surreal, pepe 2 the moon!", "tnx Zachary CEO of PEPE, pepe exchange CEO", "Pepe Founder Mr.Testa , Thank you for this giveaway 😋",
"this is really amazing, tnx pepe for this airdrop event :)", "i don't wanna miss this oppurtunity, thanks pepe", "love it! thanks pepe", "tnx pepe! feed me more!",
"can I participate again?", "CAN I JOIN ONE MORE TIME? anyway thanks pepe, +2billion pepe added to my wallet", "can i join again?", "I want more! can I join one more?",
"the best token $PEPE ^^ 2.5 Billion added to my wallet woooo!!", "tnx pepe! can I rejoin?", "x2 pepe added on my wallet 🤩", "it is possible to participate again after I doubled my pepe token? anyway thanks again pepe", "wow! this is gonna be great, tnx pepe",

"I have a dream, nevermind...", "join us on facebook: ", "​solana is strong and will break all time high. we believe in sol long term", "So who in their right mind would sell their digital assets back into usdollar? not me", "LUNC pumped SO WELL and still maintaining momentum even as BTC dipped. Great attitude by LUNC");